[tools]
"aqua:fish-shell/fish-shell" = "4.8.1"
bat = "latest"
btop = "latest"
delta = "latest"
direnv = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
hyperfine = "latest"
lazygit = "latest"
neovim = "latest"
ripgrep = "latest"
sd = "latest"
starship = "latest"
tealdeer = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
